version: "3.8"
services:
  app:
    build: .
    container_name: ecommerce-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - ./.env
    volumes:
      - .:/app
    command: npm run dev

  postgres:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
